=begin
#InternetData API

#The InternetData API. Please see https://docs.internetdata.io/api for more details. 

The version of the OpenAPI document: 2026.09.13
Contact: dev@internetdata.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module InternetData
  class DatabaseFormat
    CSVGZ = "csvgz".freeze
    MMDB = "mmdb".freeze

    def self.all_vars
      @all_vars ||= [CSVGZ, MMDB].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DatabaseFormat.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DatabaseFormat"
    end
  end
end
