=begin
#InternetData API

#The InternetData API: download the databases your organization is licensed for, and manage the account behind them.  See https://docs.internetdata.io for guides and https://github.com/internetdata for the official client libraries. 

The version of the OpenAPI document: 2026.09.21
Contact: support@internetdata.io
Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module InternetData
  class Standing
    LICENSED = "licensed".freeze
    EXPIRED = "expired".freeze
    UNLICENSED = "unlicensed".freeze

    def self.all_vars
      @all_vars ||= [LICENSED, EXPIRED, UNLICENSED].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if Standing.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #Standing"
    end
  end
end
